version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app  # Mount the backend directory
    ports:
      - "8000:8000"
    networks:
      - cap

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Assuming your frontend runs on port 5000
    depends_on:
      - backend
    networks:
      - cap
  
networks:
  cap:
